# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(related_name='works', to='libraryapi.Author'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(related_name='works', to='libraryapi.Tag'),
        ),
    ]
